apiVersion: apps/v1
kind: Deployment
metadata:
  name: bruski-beer-service-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bruski-beer-service
  template:
    metadata:
      labels:
        app: bruski-beer-service
    spec:
      containers:
        - name: bruski-beer-service
          image: kwalter26/bruski-beer-service
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: bruski-beer-service-config