version: 2.1

orbs:
  gradle: circleci/gradle@2.2.0

workflows:
  checkout-build-test:

    jobs:
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - gradle/test